1.14/sec/meetings/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('sec.meetings.views',
    url(r'^$', 'main', name='meetings'),
    url(r'^add/$', 'add', name='meetings_add'),
    #url(r'^blue_sheet/$', 'blue_sheet', name='meetings_blue_sheet'),
    url(r'^(?P<meeting_id>\d{1,6})/$', 'view', name='meetings_view'),
    url(r'^(?P<meeting_id>\d{1,6})/edit/$', 'edit_meeting',
        name='meetings_edit_meeting'),
    url(r'^(?P<meeting_id>\d{1,6})/rooms/$', 'rooms', name='meetings_rooms'),
    url(r'^(?P<meeting_id>\d{1,6})/times/$', 'times', name='meetings_times'),
    url(r'^(?P<meeting_id>\d{1,6})/times/delete/(?P<time>[0-9\:]+)/$', 'times_delete', name='meetings_times_delete'),
    url(r'^(?P<meeting_id>\d{1,6})/non_session/$', 'non_session', name='meetings_non_session'),
    url(r'^(?P<meeting_id>\d{1,6})/set_room/(?P<slot_id>\d{1,6})/$', 'set_room', name='meetings_set_room'),
    url(r'^(?P<meeting_id>\d{1,6})/non_session/delete/(?P<slot_id>\d{1,6})/$', 'non_session_delete', name='meetings_non_session_delete'),
    url(r'^(?P<meeting_id>\d{1,6})/select/$', 'select_group',
        name='meetings_select_group'),
    url(r'^(?P<meeting_id>\d{1,6})/(?P<acronym>[A-Za-z0-9_\-\+]+)/schedule/$', 'schedule', name='meetings_schedule'),
    url(r'^(?P<meeting_id>\d{1,6})/(?P<acronym>[A-Za-z0-9_\-\+]+)/remove/$', 'remove_session', name='meetings_remove_session'),
)

1.14/sec/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', direct_to_template, {'template': 'main.html'}, name="home"),
    (r'^announcement/', include('sec.announcement.urls')),
    (r'^areas/', include('sec.areas.urls')),
    (r'^drafts/', include('sec.drafts.urls')),
    (r'^groups/', include('sec.groups.urls')),
    (r'^ipr/', include('sec.ipr.urls')),
    (r'^meetings/', include('sec.meetings.urls')),
    (r'^proceedings/', include('sec.proceedings.urls')),
    (r'^roles/', include('sec.roles.urls')),
    (r'^rolodex/', include('sec.rolodex.urls')),
    (r'^sreq/', include('sec.sreq.urls')),
    (r'^telechat/', include('sec.telechat.urls')),
)

1.14/sec/meetings/forms.py
from django import forms
from django.db.models import Q

from ietf.group.models import Group
from ietf.meeting.models import Meeting, Room, TimeSlot, Session
from ietf.meeting.timedeltafield import TimedeltaFormField, TimedeltaWidget
from ietf.name.models import TimeSlotTypeName

import itertools
import re

DAYS_CHOICES = ((-1,'Saturday'),
                (0,'Sunday'),
                (1,'Monday'),
                (2,'Tuesday'),
                (3,'Wednesday'),
                (4,'Thursday'),
                (5,'Friday'))

"""
SESSION_CHOICES = list(SessionName.objects.values_list('session_name_id', 'session_name')) 
SESSION_CHOICES.insert(0,('0','-----------'))
#----------------------------------------------------------
# Helper Functions
#----------------------------------------------------------
"""
def get_next_slot(slot):
    '''Takes a TimeSlot object and returns the next TimeSlot same day and same room, None if there
    aren't any.  You must check availability of the slot as we sometimes need to get the next
    slot whether it's available or not.  For use with combine option.
    '''
    same_day_slots = TimeSlot.objects.filter(meeting=slot.meeting,location=slot.location,time__day=slot.time.day).order_by('time')
    try:
        i = list(same_day_slots).index(slot)
        return same_day_slots[i+1]
    except IndexError:
        return None
#----------------------------------------------------------
# Base Classes
#----------------------------------------------------------
class BaseMeetingRoomFormSet(forms.models.BaseInlineFormSet):
    def clean(self):
        '''Check that any rooms marked for deletion are not in use'''
        for form in self.deleted_forms:
            room = form.cleaned_data['id']
            sessions = Session.objects.filter(timeslot__location=room)
            if sessions:
                raise forms.ValidationError('Cannot delete meeting room %s.  Already assigned to some session.' % room.name)
                
class TimeSlotModelChoiceField(forms.ModelChoiceField):
    '''
    Custom ModelChoiceField, changes the label to a more readable format
    '''
    def label_from_instance(self, obj):
        
        return "%s %s - %s" % (obj.time.strftime('%a %H:%M'),obj.name,obj.location)
#----------------------------------------------------------
# Forms
#----------------------------------------------------------

class MeetingModelForm(forms.ModelForm):
    class Meta:
        model = Meeting
        exclude = ('type')
        
    def clean_number(self):
        number = self.cleaned_data['number']
        if not number.isdigit():
            raise forms.ValidationError('Meeting number must be an integer')
        return number
        
    def save(self, force_insert=False, force_update=False, commit=True):
        meeting = super(MeetingModelForm, self).save(commit=False)
        meeting.type_id = 'ietf'
        if commit:
            meeting.save()
        return meeting
        
class MeetingRoomForm(forms.ModelForm):
    class Meta:
        model = Room

class MeetingTimeForm(forms.ModelForm):
    class Meta:
        model = TimeSlot
        fields = ('day_id', 'time_desc', 'session_name_id')
        
    def __init__(self, *args, **kwargs):
        super(MeetingTimeForm, self).__init__(*args, **kwargs)
        self.fields['day_id'].widget = forms.Select(choices=DAYS_CHOICES)
        self.fields['session_name_id'].widget = forms.Select(choices=SESSION_CHOICES)
    
    def clean_time_desc(self):
        time_desc = self.cleaned_data['time_desc']
        if time_desc and time_desc != '0':
            match = re.match(r'\d{4}-\d{4}', time_desc)
            if not match:
                raise forms.ValidationError('Time must be in the from NNNN-NNNN')
        return time_desc
        
class ExtraSessionForm(forms.Form):
    no_notify = forms.BooleanField(required=False, label="Do NOT notify this action")

class NewSessionForm(forms.Form):
    time = TimeSlotModelChoiceField(queryset=TimeSlot.objects,label='Day-Time-Room',required=False)
    session = forms.CharField(widget=forms.HiddenInput)
    note = forms.CharField(max_length=255, required=False, label='Special Note from Scheduler')
    combine = forms.BooleanField(required=False, label='Combine with next session')
    
    # setup the timeslot options based on meeting passed in
    def __init__(self,*args,**kwargs):
        meeting = kwargs.pop('meeting')
        super(NewSessionForm, self).__init__(*args,**kwargs)
        
        # attach session object to the form so we can use it in the template
        self.session_object = Session.objects.get(id=self.initial['session'])
        
        # if we are editing, timeslot queryset needs to include the timeslot the session was 
        # assigned to in order to initialize the form
        if self.initial['time']:
            queryset = TimeSlot.objects.filter(Q(meeting=meeting,type='session',session__isnull=True)|
                                               Q(session__id=self.initial['session']))
        else:
            queryset = TimeSlot.objects.filter(meeting=meeting,type='session',session__isnull=True)
        self.fields['time'].queryset = queryset.order_by('time')
    
    def clean_time(self):
        time = self.cleaned_data['time']
        if time:
            if not self.session_object.requested_duration <= time.duration:
                raise forms.ValidationError('The requested session length is longer than the duration of this timeslot')
        return time
        
    def clean(self):
        super(NewSessionForm, self).clean()
        if any(self.errors):
            return
        cleaned_data = self.cleaned_data
        time = cleaned_data['time']
        if cleaned_data['combine']:
            slot = get_next_slot(cleaned_data['time'])
            if not slot or slot.session != None:
                raise forms.ValidationError('There is no next session to combine')
        
        return cleaned_data

class RoomForm(forms.Form):
    location = forms.ModelChoiceField(queryset=Room.objects)
    group = forms.ModelChoiceField(queryset=Group.objects.filter(acronym__in=('edu','ietf','iepg','tools','iesg','iab','iaoc')),
        help_text='''Select a group to associate with this session.  For example:<br>
                     Tutorials = Education,<br>
                     Code Sprint = Tools Team,<br>
                     Technical Plenary = IAB,<br>
                     Administrative Plenary = IAOC or IESG''',empty_label=None)
    
    def __init__(self,*args,**kwargs):
        meeting = kwargs.pop('meeting')
        self.session = kwargs.pop('session')
        super(RoomForm, self).__init__(*args,**kwargs)
        self.fields['location'].queryset = Room.objects.filter(meeting=meeting)
    
    def clean_group(self):
        group = self.cleaned_data['group']
        if self.session.group != group and self.session.materials.all():
            raise forms.ValidationError("ERROR: can't change group after materials have been uploaded")
        return group
        
class TimeSlotForm(forms.Form):
    day = forms.ChoiceField(choices=DAYS_CHOICES)
    time = forms.TimeField()
    duration = TimedeltaFormField(widget=TimedeltaWidget(attrs={'inputs':['hours','minutes']}))
    name = forms.CharField()

class NonSessionForm(TimeSlotForm):
    # inherit TimeSlot and add Type field
    type = forms.ModelChoiceField(queryset=TimeSlotTypeName.objects.filter(slug__in=('other','reg','break','plenary')),empty_label=None)
    show_location = forms.BooleanField(required=False)

1.14/sec/templates/meetings/blue_sheet.html
{% extends "base_site.html" %}

{% block title %}Meetings - Blue Sheet{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="/js/jquery-1.3.2.min.js"></script>
  <script type="text/javascript" src="/js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }}
  &raquo; <a href="../">Meetings</a>
  &raquo; Blue Sheet
{% endblock %}

{% block content %}

<div  class="module">
  <h2>Blue Sheet</h2>
  
  <p>
  <a href="{{ url }}">Download</a> latest Blue Sheets.
  </p>

    <div class="button-group">
       <ul>
             <li><button onclick="window.location='../../'">Back</button></li>
        </ul>
      </div> <!-- button-group -->

</div> <!-- module -->

{% endblock %}

1.14/sec/templates/meetings/non_session.html
{% extends "meetings/base_rooms_times.html" %}

{% block subsection %}

<div class="module">
    <h2>TimeSlots</h2>

    {% if slots %}
    <table class="full-width">
      <thead>
        <tr>
          <th>Day</th>
          <th>Time</th>
          <th>Duration</th>
          <th>Name</th>
          <th>Group</th>
          <th>Location</th>
          <th>Show Loc.</th>
          <th>Type</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for item in slots %}
          <tr class="{% cycle row1,row2 %}">
            <td>{{ item.time|date:"D" }}</td>
            <td>{{ item.time|date:"H:i" }}</td>
            <td>{{ item.duration }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.session.group.acronym }}</td>
            {% if item.type.slug == 'other' or item.type.slug == 'plenary' %}
              <td><a href="{% url meetings_set_room meeting_id=meeting.number slot_id=item.id %}">{{ item.location }}</a></td>
            {% else %}
              <td>{{ item.location }}</td>
            {% endif %}
            <td>{{ item.show_location }}</td>
            <td>{{ item.type }}</td>
            <td><a href="{% url meetings_non_session_delete meeting_id=meeting.number slot_id=item.id %}">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <h3>No timeslots exist for this meeting.  First add the rooms and then the app will create timeslots based on the schedule from the last meeting.</h3>
    {% endif %}
    <br /><hr />
    
    <div>
    <form id="timeslot-form" action="" method="post">
        {{ form.non_field_errors }}
        <table id="timeslot-form">
          {{ form.as_table }}
          <tr><td colspan="2" align="center"><input type="submit" name="submit" value="Add" /></td></tr>
        </table>
     </form>
     </div>
    
    <div class="button-group">
      <ul>
        <li><button onclick="window.location='../'">Back</button></li>
      </ul>
    </div> <!-- button-group -->
      
      </form>
</div> <!-- module -->


{% endblock %}

1.14/sec/templates/meetings/schedule.html
{% extends "base_site.html" %}

{% block title %}Meetings{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="/js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }}
  &raquo; <a href="../../">Meetings</a>
  &raquo; <a href="{% url meetings_view meeting_id=meeting.number %}">{{ meeting }}</a>
  &raquo; <a href="{% url meetings_select_group meeting_id=meeting.number %}">Select</a>
  &raquo; {{ group.acronym }}
{% endblock %}

{% block content %}

<div class="module">
    <h2>Requested Information</h2>
    
    {% if show_request %}
       {% include "includes/sessions_request_view.html" %}
    {% endif %}
    
    <div class="inline-group">
    <h2>Sessions</h2>

        <form id="meetings-schedule-form" method="post" action="">
        {{ formset.management_form }}
          {% for form in formset.forms %}
            <div class="inline-related{% if forloop.last %} last-related{% endif %}">
              <h3><b>Session:</b>&nbsp; #{{ forloop.counter }}{% if form.session_object.status.slug == 'apprw' %}<span class="message-right">Waiting for Approval</span>{% endif %}</h3>
              <table>
                {{ form }}
              </table>
            </div> <!-- inline-related -->
          {% endfor %}
    </div> <!-- inline-group -->
    
    <table>
    {{ extra_form }}
    </table>
    
      <div class="button-group">
       <ul>
         <li><button type="submit" name="submit" value="Save">Save</button></li>
         <li><button type="button" onclick="if (window.confirm('This group will be permanently removed from the agenda and scheduling tool')) { window.location='{% url meetings_remove_session meeting_id=meeting.id acronym=group.acronym %}' };">Remove this group from agenda</button></li>
         <li><button type="button" onclick="window.location='{% url meetings_select_group meeting_id=meeting.number %}'">Back</button></li>
        </ul>
      </div> <!-- button-group -->
      
      </form>
      
</div> <!-- module -->

{% endblock %}

1.14/sec/templates/meetings/select_group.html
{% extends "base_site.html" %}

{% block title %}Meetings{% endblock %}

{% block extrahead %}{{ block.super }}
  <script type="text/javascript" src="/js/utils.js"></script>
{% endblock %}

{% block breadcrumbs %}{{ block.super }}
  &raquo; <a href="../../">Meetings</a>
  &raquo; <a href="../">{{ meeting.number }}</a>
  &raquo; Select Group
{% endblock %}

{% block content %}

<div class="module">
    <h2>IETF {{ meeting.number }} - Schedule Sessions</h2>
      <p>The lists below contain those groups which have submitted a session request.  Select a
      group to schedule sessions.  (Proposed Working Groups are in the BOFs list).</p>
      <p>Select this link to <a href="https://datatracker.ietf.org/meeting/{{ meeting.number }}/agenda.html">View Agenda</a></p>
      
      <div class="inline-related">
        <form class="internal-form" action="" method="post">
          <label for="id_group">Working Groups</label></th>
          {{ group_form.group }}
          <input type="submit" name="submit" value="Select" />
        </form>
        <form class="internal-form" action="" method="post">
          <label for="id_group">BOFs</label>
          {{ bof_form.group }}
          <input type="submit" name="submit" value="Select" />
        </form>
        <form class="internal-form" action="" method="post">
          <label for="id_group">IRTF</label>
          {{ irtf_form.group }}
          <input type="submit" name="submit" value="Select" />
        </form>
        
      <div class="button-group">
       <ul>
         <li><button onclick="window.location='../'">Back</button></li>
       </ul>
      </div> <!-- button-group -->
      
      </div><!-- inline-related-->
      
      <div class="inline-related">
      <h2>Scheduled Sessions</h2>
        <ul>
          {% for group in scheduled_groups %}
            <li><a href="{% url meetings_schedule meeting_id=meeting.id acronym=group.acronym %}">{{ group.acronym }}</a></li>
          {% endfor %}
        </ul>
      </div><!-- inline-related-->

     
</div> <!-- module -->

{% endblock %}
 

1.14/sec/templates/meetings/set_room.html
{% extends "meetings/base_rooms_times.html" %}

{% block subsection %}

<div class="module interim-container">
    <h2>Meeting - {{ meeting }}</h2>
         <p><h3>Session: {{ slot.name }}</h3></p>
         <form enctype="multipart/form-data" action="." method="post">
           <table>
             {{ form.as_table }}
           </table>

             {% include "includes/buttons_save_cancel.html" %}

         </form>
</div> <!-- module -->

{% endblock %}

1.14/sec/templates/meetings/times.html
{% extends "meetings/base_rooms_times.html" %}

{% block subsection %}

<div class="module">
    <h2>Times</h2>

    {% if times %}
    <table class="full-width">
      <thead>
        <tr>
          <th>Day</th>
          <th>Time</th>
          <th>Duration</th>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for item in times %}
          <tr class="{% cycle row1,row2 %}">
            <td>{{ item.time|date:"D" }}</td>
            <td>{{ item.time|date:"H:i" }}</td>
            <td>{{ item.duration }}</td>
            <td>{{ item.name }}</td>
            <td><a href="{% url meetings_times_delete meeting_id=meeting.number time=item.time|date:"Y:m:d:H:i" %}">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <h3>No timeslots exist for this meeting.  First add the rooms and then the app will create timeslots based on the schedule from the last meeting.</h3>
    {% endif %}
    <br /><hr />
    
    <form action="" method="post">
        {{ form.non_field_errors }}
        <table id="timeslot-form" class="full-width">
          <tr>
            <td>Day<br>{{ form.day.errors }}{{ form.day }}</td>
            <td>Time<br>{{ form.time.errors }}{{ form.time }}</td>
            <td>Duration<br>{{ form.duration.errors }}{{ form.duration }}</td>
            <td>Name<br>{{ form.name.errors }}{{ form.name }}</td>
            <td><input type="submit" name="submit" value="Add" /></td>
          </tr>
        </table>    
      </form>
    
    <div class="button-group">
      <ul>
        <li><button onclick="window.location='../'">Back</button></li>
      </ul>
    </div> <!-- button-group -->
      
      </form>
</div> <!-- module -->

{% endblock %}